= API
ifndef::stem[:stem: latexmath]
ifndef::imagesdir[:imagesdir: ./img/]
ifndef::source-highlighter[:source-highlighter: highlightjs]
ifndef::highlightjs-theme:[:highlightjs-theme: solarized-dark]


[[Syntax]]
== Syntax

[source,js]
----
const timeFunction = (self) ⇒ { /*…​*/ self.now = value;};

const timeline = T( timeFunction );

const timeline1 = timeline.sync( someFunction );
----

== TypeScript type definition

https://github.com/stken2050/timeline-monad/blob/master/dist/esm/timeline-monad.d.ts[timeline-monad TypeScript type definition]

[source,js]
.timeline type definition
----
interface timeline {
    type: string;
    now: any;
    sync: Function;
}
declare const T: (timeFunction?: Function) => timeline;
export { T };
----


== T( __timeFunction__ )

[source,js]
----
const T: (timeFunction?: Function) => timeline
----


== __timeline__.now

[source,js]
----
const timeFunction = (self) ⇒ { /*…​*/ self.now = value;};
----

== .sync( __someFunction__ )

[source,js]
----
const timeline1 = timeline
                         .sync( someFunction );
----

[TIP]
.**timeline-monad** is extremely simple and easy to learn.
====
`T`, `now` and `sync` are the only reserved words and elements provided by the module. 


`T` is a function to return a  __timeline__ object.

__timeFunction__ is a function to define the __timeline__ behavior with the argument `self` (the __timeline__ itself).

__timeFunction__ is executed immediately by the `T` implementation, and when `self.now = value` is defined, the __someFunction__ defined in the `sync` method is evaluated. 
====

