= Simple usage
ifndef::stem[:stem: latexmath]
ifndef::imagesdir[:imagesdir: ./img/]
ifndef::source-highlighter[:source-highlighter: highlightjs]
ifndef::highlightjs-theme:[:highlightjs-theme: solarized-dark]

== Write and Read the "current" value of __timeline__

`T()` is a __timeline__ instance:

[source,js]
.timeline instance
----
const timeline = T();
----

As __timeline__ is an infinite stream of time, __timeline__ has a (in a user's perspective) "current" value: __timeline__ `.now`, and can be easily get/set as below:

[source,js]
.write and read
----
timeline.now = "Hello";
console.log(timeline.now);
----

[source,shell]
.console
----
Hello
----

++++
<iframe height="265" style="width: 100%;" scrolling="no" title="Hello Timeline" src="//codepen.io/stken2050/embed/ZwOaEr/?height=265&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/ZwOaEr/'>Hello Timeline</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++

== __timeline__.now = undefined

Unless a __timeline__ is defined along with an immidiate "current" value, the current __timeline__ value is undefined.

.timeline instance
```js
const timeline = T();
```

As long as the value of  __timeline__.now is `undefined`, __someFunction__ of __timeline__.sync(__someFunction__) is never evaluated.

The following code does nothing since the value of  __timeline__.now is `undefined`.


.timeline sync
```js
const timeline = T();
  
timeline.sync(
    a => console.log(a)
  );
```

The following code also does nothing.

.timeline sync
```js
const timeline = T();
  
timeline.sync(
    a => console.log(a)
  );

timeline.now = undefined;
```

== __timeline__.sync is declarative

On the other hand, the following code does something.

++++
<iframe height="413" style="width: 100%;" scrolling="no" title="Hello Timeline undefined01" src="//codepen.io/stken2050/embed/BMpKEb/?height=413&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/BMpKEb/'>Hello Timeline undefined01</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++


++++
<iframe height="419" style="width: 100%;" scrolling="no" title="Hello Timeline undefined02" src="//codepen.io/stken2050/embed/PVWNrV/?height=419&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/PVWNrV/'>Hello Timeline undefined02</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++


++++
<iframe height="409" style="width: 100%;" scrolling="no" title="Hello Timeline undefined03" src="//codepen.io/stken2050/embed/WPRxjQ/?height=409&theme-id=36003&default-tab=js,result" frameborder="no" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/stken2050/pen/WPRxjQ/'>Hello Timeline undefined03</a> by Ken OKABE
  (<a href='https://codepen.io/stken2050'>@stken2050</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
++++



`timelineA` value is defined as `1` at first, then later changed to `5`.

*`timelineB` is declared to be _always_ synchronized with `timelineA`, and an equation below is guaranteed to be satisfied.* 


[stem]
++++
timelineB = timelineA \times 2
++++

`timelineB` depends (relies) on `timelineA`, and after the declaration, you don't need to, or should not touch the value of `timelineB`. Of course, you can add relation and connection to other Timelines.